# Import Dataset

![image.png]()

## 1. Import CSV

In [3]:
import pandas as pd

df = pd.read_csv('IncomeData.csv')

In [5]:
df.shape

(32561, 14)

In [6]:
df.head()

,Age,Workclass,fnlwgt,Education,Education-Num,Marital Status,Occupation,Relationship,Sex,Capital Gain,Capital Loss,Hours per week,Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Female,0,0,40,Cuba,<=50K

In [7]:
df.head(10)

,Age,Workclass,fnlwgt,Education,Education-Num,Marital Status,Occupation,Relationship,Sex,Capital Gain,Capital Loss,Hours per week,Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Male,5178,0,40,United-States,>50K

In [8]:
df.tail()

,Age,Workclass,fnlwgt,Education,Education-Num,Marital Status,Occupation,Relationship,Sex,Capital Gain,Capital Loss,Hours per week,Country,Income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,Female,15024,0,40,United-States,>50K

In [9]:
df.tail(10)

,Age,Workclass,fnlwgt,Education,Education-Num,Marital Status,Occupation,Relationship,Sex,Capital Gain,Capital Loss,Hours per week,Country,Income
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,Female,15024,0,40,United-States,>50K

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             32561 non-null  int64
 1   Workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   Education       32561 non-null  object
 4   Education-Num   32561 non-null  int64
 5   Marital Status  32561 non-null  object
 6   Occupation      30718 non-null  object
 7   Relationship    32561 non-null  object
 8   Sex             32561 non-null  object
 9   Capital Gain    32561 non-null  int64
 10  Capital Loss    32561 non-null  int64
 11  Hours per week  32561 non-null  int64
 12  Country         31978 non-null  object
 13  Income          32561 non-null  object
dtypes: int64(6), object(8)
memory usage: 3.5+ MB

In [11]:
df.index

RangeIndex(start=0, stop=32561, step=1)

In [12]:
df.dtypes

Age                int64
Workclass         object
fnlwgt             int64
Education         object
Education-Num      int64
Marital Status    object
Occupation        object
Relationship      object
Sex               object
Capital Gain       int64
Capital Loss       int64
Hours per week     int64
Country           object
Income            object
dtype: object

In [13]:
df.values

array([[39, 'State-gov', 77516, ..., 40, 'United-States', '<=50K'],
       [50, 'Self-emp-not-inc', 83311, ..., 13, 'United-States', '<=50K'],
       [38, 'Private', 215646, ..., 40, 'United-States', '<=50K'],
       ...,
       [58, 'Private', 151910, ..., 40, 'United-States', '<=50K'],
       [22, 'Private', 201490, ..., 20, 'United-States', '<=50K'],
       [52, 'Self-emp-inc', 287927, ..., 40, 'United-States', '>50K']],
      dtype=object)

In [15]:
df['Workclass'].nunique()

8

In [16]:
df['Workclass'].value_counts()

Workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [18]:
df.columns

Index(['Age', 'Workclass', 'fnlwgt', 'Education', 'Education-Num',
       'Marital Status', 'Occupation', 'Relationship', 'Sex', 'Capital Gain',
       'Capital Loss', 'Hours per week', 'Country', 'Income'],
      dtype='object')

In [19]:
df['Marital Status'].nunique()

7

In [20]:
df['Marital Status'].value_counts()

Marital Status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [22]:
df.memory_usage(deep=True)

Index                 132
Age                260488
Workclass         2064314
fnlwgt             260488
Education         2130587
Education-Num      260488
Marital Status    2325313
Occupation        2205365
Relationship      2152925
Sex               2007763
Capital Gain       260488
Capital Loss       260488
Hours per week     260488
Country           2241119
Income            2010941
dtype: int64

# 2. Import excel

In [24]:
df = pd.read_excel('Pen Sales Data.xlsx')

In [25]:
df.head()

,Customer,Item,Pen Cost,Shipping Cost,Purchase Date,Delivery Date,Review
0,5201,Ballpoint Pens,5.99,2.99,2023-05-01,2023-05-03,"DoodleWithMe|I love the way this pen writes, b..."
1,5202,Sharpies,12.99,0.00,2023-05-01,2023-05-04,ScribbleMaster|The classic Sharpie marker has ...
2,5203,Ballpoint Pens (Bold),6.95,4.99,2023-05-01,2023-05-02,PenPalForever|The retractable ballpoint pen ha...
3,5204,Gel Pens,5.99,2.99,2023-05-01,2023-05-04,TheWriteWay|This gel pen has a comfortable gri...
4,5205,Rollerball Pens,12.99,1.99,2023-05-01,2023-05-03,PenAndPaperPerson|The rollerball pen has a smo...

In [26]:
df.shape

(25, 7)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer       25 non-null     int64
 1   Item           25 non-null     object
 2   Pen Cost       25 non-null     float64
 3   Shipping Cost  25 non-null     float64
 4   Purchase Date  25 non-null     datetime64[ns]
 5   Delivery Date  25 non-null     datetime64[ns]
 6   Review         25 non-null     object
dtypes: datetime64[ns](2), float64(2), int64(1), object(2)
memory usage: 1.5+ KB

In [29]:
df.tail()

,Customer,Item,Pen Cost,Shipping Cost,Purchase Date,Delivery Date,Review
20,5221,Sharpies,12.99,1.99,2023-05-02,2023-05-05,PenPrecisionPro|The retractable Sharpie marker...
21,5222,Ballpoint Pens,5.99,1.99,2023-05-02,2023-05-05,InkCollector|The ballpoint pen is lightweight ...
22,5223,Ballpoint Pens (Bold),6.95,0.00,2023-05-02,2023-05-06,PenToPaperPersonality|
23,5224,Sharpies,12.99,2.99,2023-05-02,2023-05-06,SmoothWritingScribe|This fine point Sharpie ma...
24,5225,Ballpoint Pens (Bold),6.95,2.99,2023-05-02,2023-05-07,ThePenmanshipPundit|This pen writes smoothly a...

In [30]:
df.columns

Index(['Customer', 'Item', 'Pen Cost', 'Shipping Cost', 'Purchase Date',
       'Delivery Date', 'Review'],
      dtype='object')

In [32]:
df = pd.read_excel('Pen Sales Data.xlsx' , sheet_name='Pen Costs')

In [33]:
df.head()

                     Pen   Cost
0         Ballpoint Pens   5.99
1               Sharpies  12.99
2  Ballpoint Pens (Bold)   6.95
3               Gel Pens   5.99
4        Rollerball Pens  12.99

In [34]:
df.shape

(6, 2)

## 3. Import text file

In [42]:
df = pd.read_table('happiness_data_ca.txt' , sep=',')

In [43]:
df.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003

## 4.Import json file

In [48]:
import json

# Opening JSON file
f = open('complaints-2021-05-14_08_16.json',)

# returns JSON object as
# a dictionary
data = json.load(f)
df=pd.json_normalize(data)

In [49]:
df.head()

,_index,_type,_id,_score,_source.tags,_source.zip_code,_source.complaint_id,_source.issue,_source.date_received,_source.state,...,_source.company_response,_source.company,_source.submitted_via,_source.date_sent_to_company,_source.company_public_response,_source.sub_product,_source.timely,_source.complaint_what_happened,_source.sub_issue,_source.consumer_consent_provided
0,complaint-public-v2,complaint,3211475,0.0,None,90301,3211475,Attempts to collect debt not owed,2019-04-13T12:00:00-05:00,CA,...,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-04-13T12:00:00-05:00,None,Credit card debt,Yes,,Debt is not yours,Consent not provided
1,complaint-public-v2,complaint,3229299,0.0,Servicemember,319XX,3229299,Written notification about debt,2019-05-01T12:00:00-05:00,GA,...,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-05-01T12:00:00-05:00,None,Credit card debt,Yes,Good morning my name is XXXX XXXX and I apprec...,Didn't receive enough information to verify debt,Consent provided
2,complaint-public-v2,complaint,3199379,0.0,None,77069,3199379,"Other features, terms, or problems",2019-04-02T12:00:00-05:00,TX,...,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-04-02T12:00:00-05:00,None,General-purpose credit card or charge card,Yes,I upgraded my XXXX XXXX card in XX/XX/2018 and...,Problem with rewards from credit card,Consent provided
3,complaint-public-v2,complaint,2673060,0.0,None,48066,2673060,Trouble during payment process,2017-09-13T12:00:00-05:00,MI,...,Closed with explanation,JPMORGAN CHASE & CO.,Web,2017-09-14T12:00:00-05:00,None,Conventional home mortgage,Yes,,None,Consent not provided
4,complaint-public-v2,complaint,3203545,0.0,None,10473,3203545,Fees or interest,2019-04-05T12:00:00-05:00,NY,...,Closed with explanation,JPMORGAN CHASE & CO.,Referral,2019-04-05T12:00:00-05:00,None,General-purpose credit card or charge card,Yes,,Charged too much interest,N/A

In [51]:
df.shape

(78313, 22)

In [52]:
df.head()

,_index,_type,_id,_score,_source.tags,_source.zip_code,_source.complaint_id,_source.issue,_source.date_received,_source.state,...,_source.company_response,_source.company,_source.submitted_via,_source.date_sent_to_company,_source.company_public_response,_source.sub_product,_source.timely,_source.complaint_what_happened,_source.sub_issue,_source.consumer_consent_provided
0,complaint-public-v2,complaint,3211475,0.0,None,90301,3211475,Attempts to collect debt not owed,2019-04-13T12:00:00-05:00,CA,...,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-04-13T12:00:00-05:00,None,Credit card debt,Yes,,Debt is not yours,Consent not provided
1,complaint-public-v2,complaint,3229299,0.0,Servicemember,319XX,3229299,Written notification about debt,2019-05-01T12:00:00-05:00,GA,...,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-05-01T12:00:00-05:00,None,Credit card debt,Yes,Good morning my name is XXXX XXXX and I apprec...,Didn't receive enough information to verify debt,Consent provided
2,complaint-public-v2,complaint,3199379,0.0,None,77069,3199379,"Other features, terms, or problems",2019-04-02T12:00:00-05:00,TX,...,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-04-02T12:00:00-05:00,None,General-purpose credit card or charge card,Yes,I upgraded my XXXX XXXX card in XX/XX/2018 and...,Problem with rewards from credit card,Consent provided
3,complaint-public-v2,complaint,2673060,0.0,None,48066,2673060,Trouble during payment process,2017-09-13T12:00:00-05:00,MI,...,Closed with explanation,JPMORGAN CHASE & CO.,Web,2017-09-14T12:00:00-05:00,None,Conventional home mortgage,Yes,,None,Consent not provided
4,complaint-public-v2,complaint,3203545,0.0,None,10473,3203545,Fees or interest,2019-04-05T12:00:00-05:00,NY,...,Closed with explanation,JPMORGAN CHASE & CO.,Referral,2019-04-05T12:00:00-05:00,None,General-purpose credit card or charge card,Yes,,Charged too much interest,N/A

In [54]:
df.columns

Index(['_index', '_type', '_id', '_score', '_source.tags', '_source.zip_code',
       '_source.complaint_id', '_source.issue', '_source.date_received',
       '_source.state', '_source.consumer_disputed', '_source.product',
       '_source.company_response', '_source.company', '_source.submitted_via',
       '_source.date_sent_to_company', '_source.company_public_response',
       '_source.sub_product', '_source.timely',
       '_source.complaint_what_happened', '_source.sub_issue',
       '_source.consumer_consent_provided'],
      dtype='object')

## 5. Import html file

In [63]:
# Read HTML tables from a URL
url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)'
dfs = pd.read_html(url)

In [66]:
dfs[2]

    Country/Territory IMF[1][12]            World Bank[13]             \
    Country/Territory   Forecast       Year       Estimate       Year
0               World  115494312       2025      105435540       2023
1       United States   30337162       2025       27360935       2023
2               China   19534894  [n 1]2025       17794782  [n 3]2023
3             Germany    4921563       2025        4456081       2023
4               Japan    4389326       2025        4212945       2023
..                ...        ...        ...            ...        ...
205          Kiribati        311       2024            279       2023
206             Palau        308       2024            263       2023
207  Marshall Islands        305       2024            284       2023
208             Nauru        161       2024            154       2023
209            Tuvalu         66       2024             62       2023

    United Nations[14]
              Estimate       Year
0            100834796       2022
1             25744100       2022
2             17963170  [n 1]2022
3              4076923       2022
4              4232173       2022
..                 ...        ...
205                223       2022
206                225       2022
207                279       2022
208                147       2022
209                 59       2022

[210 rows x 7 columns]

## 6. Import Parquet file

In [67]:
df = pd.read_parquet('house-price.parquet')

In [68]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [69]:
df.shape

(545, 13)

In [70]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [72]:
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

## 7. Import Feather files

In [78]:
df = pd.read_feather('/content/2018_Cities_Disclosing_to_CDP.feather')

In [79]:
df.head()

,Year Reported to CDP,Account Number,Organization,City,Country,CDP Region,Reporting Authority,Access,First Time Discloser,Population,Population Year,City Location,Last update
0,2018,58671,Helsingør Kommune / Elsinore Municipality,Helsingør,Denmark,Europe,CDP Cities,public,No,62686.0,2017,POINT (12.5921 56.0308),2020-06-25T04:52:49.050
1,2018,59167,Municipalidad de Providencia,Providencia,Chile,Latin America,CDP Cities,public,No,126487.0,2012,POINT (-70.6092 -33.4313),2020-06-25T04:52:49.050
2,2018,50553,City of Fresno,Fresno,United States of America,North America,CDP Cities,public,Yes,527438.0,2017,POINT (-119.773 36.7468),2020-06-25T04:52:49.050
3,2018,826407,Munícipio de Mirandela,Mirandela,Portugal,Europe,CDP Cities,public,Yes,11852.0,2011,POINT (-7.1753 41.51),2020-06-25T04:52:49.050
4,2018,60375,Gobiernación del Archipiélago de San Andrés,Archipiélago de San Andrés,Colombia,Latin America,CDP Cities,public,No,120000.0,2017,POINT (-81.6976 12.5794),2020-06-25T04:52:49.050

In [80]:
df.shape

(641, 13)

In [81]:
df.columns

Index(['Year Reported to CDP', 'Account Number', 'Organization', 'City',
       'Country', 'CDP Region', 'Reporting Authority', 'Access',
       'First Time Discloser', 'Population', 'Population Year',
       'City Location', 'Last update'],
      dtype='object')

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641 entries, 0 to 640
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year Reported to CDP  641 non-null    int64
 1   Account Number        641 non-null    int64
 2   Organization          641 non-null    object
 3   City                  641 non-null    object
 4   Country               641 non-null    object
 5   CDP Region            641 non-null    object
 6   Reporting Authority   641 non-null    object
 7   Access                641 non-null    object
 8   First Time Discloser  641 non-null    object
 9   Population            586 non-null    float64
 10  Population Year       641 non-null    int64
 11  City Location         641 non-null    object
 12  Last update           641 non-null    object
dtypes: float64(1), int64(3), object(9)
memory usage: 65.2+ KB

## 8. Import pickle files

In [84]:
df = pd.read_pickle('/content/groceries_with_new_columns.pkl')

In [85]:
df.head()

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.2,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.3,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.1,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.0,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.0,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday

In [86]:
df.shape

(25, 14)

In [87]:
df.tail()

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percent Inventory,Low Inventory,Last_Updated,Last_Updated_Time,Next_Scheduled_Shipment,Shipment_Date_DOW
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.1,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday
21,P100031,100031,Frozen,Frozen Snacks,Chicken Nuggets,False,6.99,85,1.8,,2023-05-28 22:02:00,22:02:00,2023-06-28,Wednesday
22,P100032,100032,Frozen,Frozen Snacks,Spinach Dip,False,4.96,76,1.6,,2023-05-28 22:05:00,22:05:00,2023-06-28,Wednesday
23,P100033,100033,Frozen,Frozen Fruit,Frozen Blueberries,False,10.99,162,3.3,,2023-05-28 22:14:00,22:14:00,2023-06-28,Wednesday
24,P100034,100034,Frozen,Frozen Fruit,Frozen Pineapple,False,7.96,178,3.7,,2023-05-28 22:11:00,22:11:00,2023-06-28,Wednesday

In [88]:
df.columns

Index(['Product_ID', 'Product_ID_Num', 'Category', 'Subcategory', 'Item',
       'Organic', 'Price_Dollars', 'Inventory', 'Percent Inventory',
       'Low Inventory', 'Last_Updated', 'Last_Updated_Time',
       'Next_Scheduled_Shipment', 'Shipment_Date_DOW'],
      dtype='object')